[package]
name = "todo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
colored = "2.1.0"
ctrlc = "3.4.4"
indicatif = "0.17.8"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
